In [32]:
# -*- coding: utf-8 -*-
import numpy as np
%matplotlib inline
import matplotlib.pyplot as plt
import time
import utils
import GCFBv211 as gcfb_Main
import csv

In [33]:
class GCparam_default:
    fs = 48000
    NumCh = 100
    FRange = np.array([100, 6000])
    OutMidCrct = "No"

In [34]:
# Stiuli : a simple pulse train
fs = 48000
Tp = 10 # (ms) 100 Hz pulse train
Snd = np.array(([1]+[0]*int(Tp*fs/1000-1))*10)
Tsnd = len(Snd)/fs
print("Duration of sound = {} (ms)".format(Tsnd*1000))

Duration of sound = 100.0 (ms)


In [35]:
SigSPL = 40
GCparam_Ctrl = 'dynamic'

In [36]:
# Level equalization
Snd, _ = utils.Eqlz2MeddisHCLevel(Snd, SigSPL)

# GCFB
GCparam = GCparam_default() # reset all
GCparam.Ctrl = GCparam_Ctrl
cGCout, pGCout, GCparam, GCrest = gcfb_Main.GCFBv211(Snd, GCparam)

*** No Outer/Middle Ear correction ***
*** Gammachirp Calculation ***
--- Channel-by-channel processing ---
Passive-Gammachirp & Level estimation filter ch #1 / #100.   elapsed time = 0.1 (sec)
Passive-Gammachirp & Level estimation filter ch #20 / #100.   elapsed time = 0.2 (sec)
Passive-Gammachirp & Level estimation filter ch #40 / #100.   elapsed time = 0.4 (sec)
Passive-Gammachirp & Level estimation filter ch #60 / #100.   elapsed time = 0.6 (sec)
Passive-Gammachirp & Level estimation filter ch #80 / #100.   elapsed time = 0.8 (sec)
Passive-Gammachirp & Level estimation filter ch #100 / #100.   elapsed time = 0.9 (sec)
--- Sample-by-sample processing ---
ACFilterBank: Initialization of ACFstatus
Dynamic Compressive-Gammachirp: Time 0.0 (ms) / 100.0 (ms). elapsed time = 0.0 (sec)
Dynamic Compressive-Gammachirp: Time 10.0 (ms) / 100.0 (ms). elapsed time = 2.4 (sec)
Dynamic Compressive-Gammachirp: Time 20.0 (ms) / 100.0 (ms). elapsed time = 3.9 (sec)
Dynamic Compressive-Gammachirp: Tim

In [37]:
name_file = "./original/GCFBv211_cGCout_{}_{}dBSPL.csv".format(GCparam.Ctrl, SigSPL)
name_file

'./original/GCFBv211_cGCout_dynamic_40dBSPL.csv'

In [38]:
with open(name_file, "r") as csv_file:
    reader = csv.reader(csv_file, delimiter=",")
    cGCout_org = [row for row in reader]

cGCout_org = np.array(cGCout_org).astype(float)

rmse = utils.rms(cGCout_org - cGCout)
rmse

1.1142945114843323e-05

In [39]:
name_file = "./original/GCFBv211_pGCout_{}_{}dBSPL.csv".format(GCparam.Ctrl, SigSPL)
name_file

'./original/GCFBv211_pGCout_dynamic_40dBSPL.csv'

In [40]:
with open(name_file, "r") as csv_file:
    reader = csv.reader(csv_file, delimiter=",")
    pGCout_org = [row for row in reader]

pGCout_org = np.array(pGCout_org).astype(float)

rmse = utils.rms(pGCout_org - pGCout)
rmse

6.0159431314025415e-06

In [41]:
pGCout_org[0,0:10]

array([-3.4694e-17,  6.3045e-08,  5.2690e-07, -1.9049e-06, -7.6619e-06,
       -1.2850e-05, -1.2483e-05, -2.6727e-06,  1.8524e-05,  5.1055e-05])

In [42]:
pGCout[0,0:10]

array([ 0.00000000e+00,  6.30446860e-08,  5.26895566e-07, -1.90494892e-06,
       -7.66188876e-06, -1.28501156e-05, -1.24829508e-05, -2.67269167e-06,
        1.85241052e-05,  5.10552974e-05])

In [43]:
SigSPL = 60
GCparam_Ctrl = 'dynamic'

In [44]:
# Level equalization
Snd, _ = utils.Eqlz2MeddisHCLevel(Snd, SigSPL)

# GCFB
GCparam = GCparam_default() # reset all
GCparam.Ctrl = GCparam_Ctrl
cGCout, pGCout, GCparam, GCrest = gcfb_Main.GCFBv211(Snd, GCparam)

*** No Outer/Middle Ear correction ***
*** Gammachirp Calculation ***
--- Channel-by-channel processing ---
Passive-Gammachirp & Level estimation filter ch #1 / #100.   elapsed time = 0.0 (sec)
Passive-Gammachirp & Level estimation filter ch #20 / #100.   elapsed time = 0.2 (sec)
Passive-Gammachirp & Level estimation filter ch #40 / #100.   elapsed time = 0.2 (sec)
Passive-Gammachirp & Level estimation filter ch #60 / #100.   elapsed time = 0.3 (sec)
Passive-Gammachirp & Level estimation filter ch #80 / #100.   elapsed time = 0.4 (sec)
Passive-Gammachirp & Level estimation filter ch #100 / #100.   elapsed time = 0.4 (sec)
--- Sample-by-sample processing ---
ACFilterBank: Initialization of ACFstatus
Dynamic Compressive-Gammachirp: Time 0.0 (ms) / 100.0 (ms). elapsed time = 0.0 (sec)
Dynamic Compressive-Gammachirp: Time 10.0 (ms) / 100.0 (ms). elapsed time = 1.6 (sec)
Dynamic Compressive-Gammachirp: Time 20.0 (ms) / 100.0 (ms). elapsed time = 3.4 (sec)
Dynamic Compressive-Gammachirp: Tim

In [45]:
name_file = "./original/GCFBv211_cGCout_{}_{}dBSPL.csv".format(GCparam.Ctrl, SigSPL)
name_file

'./original/GCFBv211_cGCout_dynamic_60dBSPL.csv'

In [46]:
with open(name_file, "r") as csv_file:
    reader = csv.reader(csv_file, delimiter=",")
    cGCout_org = [row for row in reader]

cGCout_org = np.array(cGCout_org).astype(float)

rmse = utils.rms(cGCout_org - cGCout)
rmse

2.459894709608267e-05

In [47]:
SigSPL = 80
GCparam_Ctrl = 'dynamic'

In [48]:
# Level equalization
Snd, _ = utils.Eqlz2MeddisHCLevel(Snd, SigSPL)

# GCFB
GCparam = GCparam_default() # reset all
GCparam.Ctrl = GCparam_Ctrl
cGCout, pGCout, GCparam, GCrest = gcfb_Main.GCFBv211(Snd, GCparam)

*** No Outer/Middle Ear correction ***
*** Gammachirp Calculation ***
--- Channel-by-channel processing ---
Passive-Gammachirp & Level estimation filter ch #1 / #100.   elapsed time = 0.0 (sec)
Passive-Gammachirp & Level estimation filter ch #20 / #100.   elapsed time = 0.2 (sec)
Passive-Gammachirp & Level estimation filter ch #40 / #100.   elapsed time = 0.5 (sec)
Passive-Gammachirp & Level estimation filter ch #60 / #100.   elapsed time = 0.7 (sec)
Passive-Gammachirp & Level estimation filter ch #80 / #100.   elapsed time = 0.8 (sec)
Passive-Gammachirp & Level estimation filter ch #100 / #100.   elapsed time = 0.9 (sec)
--- Sample-by-sample processing ---
ACFilterBank: Initialization of ACFstatus
Dynamic Compressive-Gammachirp: Time 0.0 (ms) / 100.0 (ms). elapsed time = 0.0 (sec)
Dynamic Compressive-Gammachirp: Time 10.0 (ms) / 100.0 (ms). elapsed time = 1.2 (sec)
Dynamic Compressive-Gammachirp: Time 20.0 (ms) / 100.0 (ms). elapsed time = 2.4 (sec)
Dynamic Compressive-Gammachirp: Tim

In [49]:
name_file = "./original/GCFBv211_cGCout_{}_{}dBSPL.csv".format(GCparam.Ctrl, SigSPL)
name_file

'./original/GCFBv211_cGCout_dynamic_80dBSPL.csv'

In [50]:
with open(name_file, "r") as csv_file:
    reader = csv.reader(csv_file, delimiter=",")
    cGCout_org = [row for row in reader]

cGCout_org = np.array(cGCout_org).astype(float)

rmse = utils.rms(cGCout_org - cGCout)
rmse

0.00017378971212657205

In [51]:
name_file = "./original/GCFBv211_pGCout_{}_{}dBSPL.csv".format(GCparam.Ctrl, SigSPL)
name_file

'./original/GCFBv211_pGCout_dynamic_80dBSPL.csv'

In [52]:
with open(name_file, "r") as csv_file:
    reader = csv.reader(csv_file, delimiter=",")
    pGCout_org = [row for row in reader]

pGCout_org = np.array(pGCout_org).astype(float)

rmse = utils.rms(pGCout_org - pGCout)
rmse

0.0006015943131402402

In [58]:
rmse_ch = np.zeros(100)
for nch in range(100):
    rmse_ch[nch] = utils.rms(cGCout_org[nch,:]-cGCout[nch,:])
    

In [60]:
20*np.log10(rmse_ch)

array([-71.99384688, -72.85309885, -72.75520375, -71.99650397,
       -72.18395022, -72.95151582, -75.24743386, -74.70175324,
       -74.35202774, -72.69812408, -72.17265626, -72.28386019,
       -72.45911912, -72.71626372, -73.86235505, -73.87143111,
       -72.7190723 , -72.22259999, -71.93955803, -72.1482603 ,
       -72.52108032, -73.22641155, -72.79242396, -72.28277445,
       -72.13511951, -72.85385128, -73.35072317, -73.4404467 ,
       -72.9640862 , -72.84000328, -72.86521163, -73.20644395,
       -73.6159266 , -73.36698566, -73.59594234, -73.7819676 ,
       -74.08118184, -73.7393425 , -74.0805588 , -74.55062225,
       -74.21962733, -74.15698007, -74.40968197, -74.64467775,
       -74.37279135, -74.78703675, -74.57079702, -75.16117336,
       -75.05398143, -74.49108424, -75.21780095, -75.6179942 ,
       -75.26498576, -75.19915987, -75.59545677, -76.4464078 ,
       -75.69799991, -75.67013031, -76.18181989, -76.78476123,
       -77.08213673, -76.82106737, -76.71479111, -77.02